// FoodBridge Seed Data — Realistic demo data
import {
  User,
  NGOProfile,
  Donation,
  MatchSuggestion,
  DeliveryJob,
  AnalyticsSnapshot,
} from '@/types';

// ─── Users ─────────────────────────────────────────────────
export const seedUsers: User[] = [
  {
    id: 'user-donor-1',
    name: 'Raj Patel',
    email: 'donor@foodbridge.demo',
    password: 'demo123',
    role: 'donor',
    organizationName: 'Patel Family Restaurant',
    phone: '+44 20 7123 4567',
    area: 'Covent Garden, London',
    createdAt: '2025-11-15T09:00:00Z',
  },
  {
    id: 'user-ngo-1',
    name: 'Sarah Mitchell',
    email: 'ngo@foodbridge.demo',
    password: 'demo123',
    role: 'ngo',
    organizationName: 'City Harvest London',
    phone: '+44 20 7456 7890',
    area: 'Bermondsey, London',
    createdAt: '2025-10-01T09:00:00Z',
  },
  {
    id: 'user-ngo-2',
    name: 'James Chen',
    email: 'ngo2@foodbridge.demo',
    password: 'demo123',
    role: 'ngo',
    organizationName: 'FoodCycle Southwark',
    phone: '+44 20 7567 8901',
    area: 'Southwark, London',
    createdAt: '2025-10-10T09:00:00Z',
  },
  {
    id: 'user-delivery-1',
    name: 'Marcus Thompson',
    email: 'delivery@foodbridge.demo',
    password: 'demo123',
    role: 'delivery',
    organizationName: 'GreenWheels Logistics',
    phone: '+44 20 7678 9012',
    area: 'Central London',
    createdAt: '2025-11-01T09:00:00Z',
  },
];

// ─── NGO Profiles ──────────────────────────────────────────
export const seedNGOProfiles: NGOProfile[] = [
  {
    id: 'ngo-profile-1',
    userId: 'user-ngo-1',
    name: 'City Harvest London',
    supportedFoodTypes: ['cooked_meals', 'bakery', 'fresh_produce', 'packaged', 'dairy'],
    maxDailyCapacity: 200,
    area: 'Bermondsey, London',
    latitude: 51.4975,
    longitude: -0.0799,
    acceptanceRate: 0.92,
    activeStatus: true,
  },
  {
    id: 'ngo-profile-2',
    userId: 'user-ngo-2',
    name: 'FoodCycle Southwark',
    supportedFoodTypes: ['cooked_meals', 'fresh_produce', 'bakery'],
    maxDailyCapacity: 80,
    area: 'Southwark, London',
    latitude: 51.5035,
    longitude: -0.0926,
    acceptanceRate: 0.78,
    activeStatus: true,
  },
];

// ─── Donations ─────────────────────────────────────────────
const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

export const seedDonations: Donation[] = [
  {
    id: 'don-1',
    donorId: 'user-donor-1',
    title: '45 Chicken Biryani Portions',
    category: 'cooked_meals',
    foodType: 'Indian Cuisine',
    quantity: 45,
    unit: 'portions',
    urgency: 'high',
    preparedAt: hoursAgo(2),
    expiresAt: hoursFromNow(4),
    pickupStart: hoursAgo(0.5),
    pickupEnd: hoursFromNow(2),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Catering event cancelled. All portions sealed in containers.',
    isVegetarian: false,
    status: 'delivered',
    acceptedByNgoId: 'user-ngo-1',
    createdAt: daysAgo(6),
  },
  {
    id: 'don-2',
    donorId: 'user-donor-1',
    title: '20 Vegetable Samosa Trays',
    category: 'cooked_meals',
    foodType: 'Indian Snacks',
    quantity: 20,
    unit: 'trays',
    urgency: 'medium',
    preparedAt: daysAgo(5),
    expiresAt: daysAgo(4.5),
    pickupStart: daysAgo(5),
    pickupEnd: daysAgo(4.8),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Fresh vegetable samosas, suitable for reheating.',
    isVegetarian: true,
    status: 'delivered',
    acceptedByNgoId: 'user-ngo-2',
    createdAt: daysAgo(5),
  },
  {
    id: 'don-3',
    donorId: 'user-donor-1',
    title: '15kg Fresh Naan Bread',
    category: 'bakery',
    foodType: 'Bread',
    quantity: 15,
    unit: 'kg',
    urgency: 'medium',
    preparedAt: daysAgo(4),
    expiresAt: daysAgo(3.5),
    pickupStart: daysAgo(4),
    pickupEnd: daysAgo(3.8),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'End of day surplus naan bread.',
    isVegetarian: true,
    status: 'delivered',
    acceptedByNgoId: 'user-ngo-1',
    createdAt: daysAgo(4),
  },
  {
    id: 'don-4',
    donorId: 'user-donor-1',
    title: '30 Mixed Curry Portions',
    category: 'cooked_meals',
    foodType: 'Indian Cuisine',
    quantity: 30,
    unit: 'portions',
    urgency: 'high',
    preparedAt: daysAgo(3),
    expiresAt: daysAgo(2.5),
    pickupStart: daysAgo(3),
    pickupEnd: daysAgo(2.8),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Lamb Rogan Josh and Paneer Tikka Masala.',
    isVegetarian: false,
    status: 'delivered',
    acceptedByNgoId: 'user-ngo-1',
    createdAt: daysAgo(3),
  },
  {
    id: 'don-5',
    donorId: 'user-donor-1',
    title: '10 Fruit Salad Boxes',
    category: 'fresh_produce',
    foodType: 'Fresh Fruit',
    quantity: 10,
    unit: 'boxes',
    urgency: 'low',
    preparedAt: daysAgo(2),
    expiresAt: daysAgo(1),
    pickupStart: daysAgo(2),
    pickupEnd: daysAgo(1.8),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Pre-cut seasonal fruit mix.',
    isVegetarian: true,
    status: 'delivered',
    acceptedByNgoId: 'user-ngo-2',
    createdAt: daysAgo(2),
  },
  {
    id: 'don-6',
    donorId: 'user-donor-1',
    title: '25 Butter Chicken Portions',
    category: 'cooked_meals',
    foodType: 'Indian Cuisine',
    quantity: 25,
    unit: 'portions',
    urgency: 'high',
    preparedAt: hoursAgo(3),
    expiresAt: hoursFromNow(3),
    pickupStart: hoursAgo(1),
    pickupEnd: hoursFromNow(1.5),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Evening service over-prep. Excellent quality.',
    isVegetarian: false,
    status: 'in_transit',
    acceptedByNgoId: 'user-ngo-1',
    createdAt: hoursAgo(3),
  },
  {
    id: 'don-7',
    donorId: 'user-donor-1',
    title: '8 Paneer Wrap Boxes',
    category: 'cooked_meals',
    foodType: 'Indian Wraps',
    quantity: 8,
    unit: 'boxes',
    urgency: 'medium',
    preparedAt: hoursAgo(4),
    expiresAt: hoursFromNow(6),
    pickupStart: hoursAgo(2),
    pickupEnd: hoursFromNow(3),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Lunch surplus wraps with mint chutney.',
    isVegetarian: true,
    status: 'accepted',
    acceptedByNgoId: 'user-ngo-2',
    createdAt: hoursAgo(4),
  },
  {
    id: 'don-8',
    donorId: 'user-donor-1',
    title: '12 Mango Lassi Bottles',
    category: 'beverages',
    foodType: 'Beverages',
    quantity: 12,
    unit: 'bottles',
    urgency: 'low',
    preparedAt: hoursAgo(5),
    expiresAt: hoursFromNow(20),
    pickupStart: hoursAgo(3),
    pickupEnd: hoursFromNow(5),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Fresh mango lassi, sealed bottles.',
    isVegetarian: true,
    status: 'open',
    createdAt: hoursAgo(5),
  },
  {
    id: 'don-9',
    donorId: 'user-donor-1',
    title: '5kg Rice Pilaf',
    category: 'cooked_meals',
    foodType: 'Indian Rice',
    quantity: 5,
    unit: 'kg',
    urgency: 'medium',
    preparedAt: hoursAgo(2),
    expiresAt: hoursFromNow(8),
    pickupStart: hoursAgo(1),
    pickupEnd: hoursFromNow(3),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Saffron rice with peas and raisins.',
    isVegetarian: true,
    status: 'open',
    createdAt: hoursAgo(2),
  },
  {
    id: 'don-10',
    donorId: 'user-donor-1',
    title: '18 Tandoori Chicken Portions',
    category: 'cooked_meals',
    foodType: 'Indian Cuisine',
    quantity: 18,
    unit: 'portions',
    urgency: 'high',
    preparedAt: hoursAgo(1),
    expiresAt: hoursFromNow(3),
    pickupStart: hoursAgo(0.5),
    pickupEnd: hoursFromNow(1),
    locationName: 'Patel Family Restaurant, Covent Garden',
    latitude: 51.5117,
    longitude: -0.1240,
    notes: 'Event order cancelled last minute. Ready to go now.',
    isVegetarian: false,
    status: 'open',
    createdAt: hoursAgo(1),
  },
];

// ─── Match Suggestions ────────────────────────────────────
export const seedMatchSuggestions: MatchSuggestion[] = [
  // Matches for don-8 (open)
  {
    id: 'match-1',
    donationId: 'don-8',
    ngoId: 'user-ngo-1',
    score: 88,
    reason: 'Close proximity (2.1 km), accepts beverages, high capacity available, 92% acceptance rate.',
    rank: 1,
  },
  {
    id: 'match-2',
    donationId: 'don-8',
    ngoId: 'user-ngo-2',
    score: 71,
    reason: 'Nearby (3.4 km), but beverages not in primary categories. Good acceptance history.',
    rank: 2,
  },
  // Matches for don-9 (open)
  {
    id: 'match-3',
    donationId: 'don-9',
    ngoId: 'user-ngo-1',
    score: 94,
    reason: 'Excellent match — close (2.1 km), accepts cooked meals, high capacity, strong urgent-response history.',
    rank: 1,
  },
  {
    id: 'match-4',
    donationId: 'don-9',
    ngoId: 'user-ngo-2',
    score: 82,
    reason: 'Good match — moderate distance (3.4 km), accepts cooked meals, adequate capacity.',
    rank: 2,
  },
  // Matches for don-10 (open, urgent)
  {
    id: 'match-5',
    donationId: 'don-10',
    ngoId: 'user-ngo-1',
    score: 96,
    reason: 'Top match for urgent donation — closest NGO (2.1 km), accepts cooked meals, high capacity, 92% acceptance rate with strong urgent-response track record.',
    rank: 1,
  },
  {
    id: 'match-6',
    donationId: 'don-10',
    ngoId: 'user-ngo-2',
    score: 79,
    reason: 'Good option — 3.4 km away, cooked meals supported, but lower capacity and acceptance rate.',
    rank: 2,
  },
];

// ─── Delivery Jobs ─────────────────────────────────────────
export const seedDeliveryJobs: DeliveryJob[] = [
  {
    id: 'job-1',
    donationId: 'don-1',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-1',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'City Harvest London, Bermondsey, London SE1 3UW',
    etaMinutes: 22,
    distanceKm: 4.8,
    status: 'delivered',
    donationTitle: '45 Chicken Biryani Portions',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5.8),
  },
  {
    id: 'job-2',
    donationId: 'don-2',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-2',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'FoodCycle Southwark, London SE1 1TL',
    etaMinutes: 18,
    distanceKm: 3.2,
    status: 'delivered',
    donationTitle: '20 Vegetable Samosa Trays',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4.7),
  },
  {
    id: 'job-3',
    donationId: 'don-3',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-1',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'City Harvest London, Bermondsey, London SE1 3UW',
    etaMinutes: 22,
    distanceKm: 4.8,
    status: 'delivered',
    donationTitle: '15kg Fresh Naan Bread',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3.7),
  },
  {
    id: 'job-4',
    donationId: 'don-4',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-1',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'City Harvest London, Bermondsey, London SE1 3UW',
    etaMinutes: 22,
    distanceKm: 4.8,
    status: 'delivered',
    donationTitle: '30 Mixed Curry Portions',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2.7),
  },
  {
    id: 'job-5',
    donationId: 'don-6',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-1',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'City Harvest London, Bermondsey, London SE1 3UW',
    etaMinutes: 22,
    distanceKm: 4.8,
    status: 'in_transit',
    donationTitle: '25 Butter Chicken Portions',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(0.5),
  },
  {
    id: 'job-6',
    donationId: 'don-7',
    donorId: 'user-donor-1',
    ngoId: 'user-ngo-2',
    deliveryPartnerId: 'user-delivery-1',
    pickupAddress: 'Patel Family Restaurant, Covent Garden, London WC2E 8RF',
    dropAddress: 'FoodCycle Southwark, London SE1 1TL',
    etaMinutes: 18,
    distanceKm: 3.2,
    status: 'assigned',
    donationTitle: '8 Paneer Wrap Boxes',
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
];

// ─── Analytics Snapshots ───────────────────────────────────
export const seedAnalytics: AnalyticsSnapshot[] = Array.from({ length: 14 }, (_, i) => ({
  id: `analytics-${i + 1}`,
  ngoId: 'user-ngo-1',
  date: daysAgo(13 - i),
  donationsReceived: Math.floor(Math.random() * 5) + 2,
  mealsRescued: Math.floor(Math.random() * 80) + 20,
  avgAcceptanceTime: Math.floor(Math.random() * 20) + 5,
  topCategory: (['cooked_meals', 'bakery', 'fresh_produce'] as const)[Math.floor(Math.random() * 3)],
  summaryText: '',
}));
